<div class="item" data-value="EUR">EUR</div>
<div class="item" data-value="USD">USD</div>
<div class="item" data-value="JPY">JPY</div>
<div class="item" data-value="BGN">BGN</div>
<div class="item" data-value="CZK">CZK</div>
<div class="item" data-value="DKK">DKK</div>
<div class="item" data-value="GBP">GBP</div>
<div class="item" data-value="HUF">HUF</div>
<div class="item" data-value="PLN">PLN</div>
<div class="item" data-value="RON">RON</div>
<div class="item" data-value="SEK">SEK</div>
<div class="item" data-value="CHF">CHF</div>
<div class="item" data-value="ISK">ISK</div>
<div class="item" data-value="NOK">NOK</div>
<div class="item" data-value="HRK">HRK</div>
<div class="item" data-value="RUB">RUB</div>
<div class="item" data-value="TRY">TRY</div>
<div class="item" data-value="AUD">AUD</div>
<div class="item" data-value="BRL">BRL</div>
<div class="item" data-value="CAD">CAD</div>
<div class="item" data-value="CNY">CNY</div>
<div class="item" data-value="HKD">HKD</div>
<div class="item" data-value="IDR">IDR</div>
<div class="item" data-value="ILS">ILS</div>
<div class="item" data-value="INR">INR</div>
<div class="item" data-value="KRW">KRW</div>
<div class="item" data-value="MXN">MXN</div>
<div class="item" data-value="MYR">MYR</div>
<div class="item" data-value="NZD">NZD</div>
<div class="item" data-value="PHP">PHP</div>
<div class="item" data-value="SGD">SGD</div>
<div class="item" data-value="THB">THB</div>
<div class="item" data-value="ZAR">ZAR</div>
