const currencyDict = {
    EUR: '€',
    CNY: '¥',
    USD: '$',
    JPY: '¥',
    BGN: 'лв',
    CZK: 'Kč',
    DKK: 'kr',
    GBP: '£',
    HUF: 'Ft',
    PLN: 'zł',
    RON: 'lei',
    SEK: 'kr',
    CHF: 'CHF',
    ISK: 'kr',
    NOK: 'kr',
    HRK: 'kn',
    RUB: '₽',
    TRY: '₺',
    AUD: '$',
    BRL: 'R$',
    CAD: '$',
    HKD: '$',
    IDR: 'Rp',
    ILS: '₪',
    INR: '₹',
    KRW: '₩',
    MXN: '$',
    MYR: 'RM',
    NZD: '$',
    PHP: '₱',
    SGD: '$',
    THB: '฿',
    ZAR: 'R',
};

export {currencyDict};